ALL_INVESTMENT_OPTIONS = {
    "mutual_funds": [
        {
            "name": "quant small cap fund direct growth",
            "one_year_return": "10.2%",
            "three_year_return": "55.2%",
            "five_year_return": "23.49%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "Quant tax plan direct growth",
            "one_year_return": "13%",
            "three_year_return": "40.12%",
            "five_year_return": "22.77%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "TATA small cap fund direct growth",
            "one_year_return": "10.9%",
            "three_year_return": "33.6%",
            "five_year_return": "12.23%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "Kotak small cap fund direct growth",
            "one_year_return": "0.55%",
            "three_year_return": "32.59%",
            "five_year_return": "15.63%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "Quant Small Cap Fund Direct Growth",
            "one_year_return": "10.2%",
            "three_year_return": "55.2%",
            "five_year_return": "23.49%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "Quant tax plan direct growth",
            "one_year_return": "13%",
            "three_year_return": "40.12%",
            "five_year_return": "22.77%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "TATA small cap fund direct growth",
            "one_year_return": "10.9%",
            "three_year_return": "33.6%",
            "five_year_return": "12.23%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "Kotak small cap fund direct growth",
            "one_year_return": "0.55%",
            "three_year_return": "32.59%",
            "five_year_return": "15.63%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "Quant Absolute Fund Direct Growth",
            "one_year_return": "14.19%",
            "three_year_return": "31.4%",
            "five_year_return": "19.49%",
            "risk": "high",
            "category": "hybrid",
        },
        {
            "name": "JM Equity hybrid fund direct growth",
            "one_year_return": "9.83%",
            "three_year_return": "20.4%",
            "five_year_return": "11.1%",
            "risk": "high",
            "category": "hybrid",
        },
        {
            "name": "ICICI prudential multi asset direct fund growth",
            "one_year_return": "18.1%",
            "three_year_return": "20.78%",
            "five_year_return": "13.57%",
            "risk": "high",
            "category": "hybrid",
        },
        {
            "name": "Kotak equity hybrid fund direct growth",
            "one_year_return": "7.17%",
            "three_year_return": "17.49%",
            "five_year_return": "12.3%",
            "risk": "high",
            "category": "hybrid",
        },
        {
            "name": "JM low duration fund direct plan growth",
            "one_year_return": "4.61%",
            "three_year_return": "11.30%",
            "five_year_return": "5.30%",
            "risk": "Low ",
            "Category": "debt",
        },
        {
            "name": "UTI dynamic bond fund direct growth",
            "one_year_return": "10.86%",
            "three_year_return": "9.54%",
            "five_year_return": "6.17%",
            "risk": "low",
            "Category": "debt",
        },
        {
            "name": "HDFC fixed maturity plan 1141 days ",
            "one_year_return": "9.19%",
            "three_year_return": "9.52%",
            "five_year_return": "",
            "risk": "low",
            "Category": "debt",
        },
        {
            "name": "Bank of India short term income fund direct growth",
            "one_year_return": "27.43%",
            "three_year_return": "9.45%",
            "five_year_return": "4.04%",
            "risk": "low ",
            "Category": "debt",
        },
    ],
    "stocks": [
        {
            "name": "Apple Inc",
            "current_price": "$130.12",
            "one_month": "-10.72%",
            "three_months": "-11,54%",
            "one_year": "-29.74%",
            "five_year": "197.91%",
        },
        {
            "name": "Microsoft Corporation",
            "current_price": "$241.16",
            "one_month": "-2.41%",
            "three_months": "-1.25%",
            "one_year": "-31.41%",
            "five_year": "174.18%",
        },
        {
            "name": "Nvidia corporation",
            "current_price": "$145.79",
            "one_month": "-10.25%",
            "three_months": "14.86%",
            "one_year": "-53.21%",
            "five_year": "190.15%",
        },
        {
            "name": "Meta Platform Inc",
            "current_price": "$120.67",
            "one_month": "5.63%",
            "three_months": "-15.24%",
            "one_year": "-66.29%",
            "five_year": "-34.48%",
        },
        {
            "name": "Cisco System Inc",
            "current_price": "$47.61",
            "one_month": "-2.51%",
            "three_months": "16.02%",
            "one_year": "-26.41%",
            "five_year": "22.9%",
        },
    ],
    "crypto": [
        {"name": "Bitcoin", "price": "1439600", "category": "large_cap"},
        {"name": "Ethereum", "price": "102831", "category": "large_cap"},
        {"name": "Binance coin", "price": "21305", "category": "large_cap"},
        {"name": "Solana", "price": "800.26", "category": "large_cap"},
        {"name": "Tether", "price": "87.15", "category": "large_cap"},
        {"name": "Ripple", "price": "30.3", "category": "large_cap"},
        {"name": "Cardano", "price": "21.25", "category": "large_cap"},
        {"name": "Doge", "price": "6.25", "category": "large_cap"},
    ],
    "bonds": [
        [
            {
                "name": "UTI Bond Fund Direct Growth",
                "one_year_return": "10.28%",
                "three_year_return": "7.19%",
                "five_year_return": "-4.17%",
            },
            {
                "name": "Nippon India Income Fund (Growth)",
                "one_year_return": "-3.33%",
                "three_year_return": "4.96%",
                "five_year_return": "6.46%",
            },
            {
                "name": "ICICI Prudential Long Term Bond Fund Direct Plan Growth",
                "one_year_return": "-1.86%",
                "three_year_return": "4.71%",
                "five_year_return": "6.82%",
            },
            {
                "name": "Tata Income Fund Direct Growth",
                "one_year_return": "-0.50%",
                "three_year_return": "5.97%",
                "five_year_return": "-5.89%",
            },
            {
                "name": "LIC MF Bond Fund Growth",
                "one_year_return": "-2.85%",
                "three_year_return": "4.26%",
                "five_year_return": "5.26%",
            },
        ]
    ],
    "fd": [
        {
            "bank_name": "Kotak Mahindra Bank",
            "interest_rate": "7",
            "min_amount": "5000",
        },
        {"bank_name": "IND super Saver FD", "interest_rate": "8", "min_amount": "5000"},
        {
            "bank_name": "Bajaj Finance Ltd ",
            "interest_rate": "7.94",
            "min_amount": "15000",
        },
        {"bank_name": "ICICI Bank", "interest_rate": "7", "min_amount": "5000"},
        {"bank_name": "Axis Bank", "interest_rate": "6.9", "min_amount": "5000"},
    ],
    "rd": [
        {
            "tenure": "12 months",
            "bank_name": "Kotak Mahindra Bank",
            "interest_rate": "6.75",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "IND super Saver FD",
            "interest_rate": "8",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "Bajaj Finance Ltd ",
            "interest_rate": "7.94",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "ICICI Bank",
            "interest_rate": "5.7",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "Axis Bank",
            "interest_rate": "6",
            "min_amount": "1000",
        },
    ],
    "ppf": [{}],
    "nps": [{}],
}
HIGH_RISK = {
    "mutual_funds": [
        {
            "name": "quant small cap fund direct growth",
            "one_year_return": "10.2%",
            "three_year_return": "55.2%",
            "five_year_return": "23.49%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "Quant tax plan direct growth",
            "one_year_return": "13%",
            "three_year_return": "40.12%",
            "five_year_return": "22.77%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "TATA small cap fund direct growth",
            "one_year_return": "10.9%",
            "three_year_return": "33.6%",
            "five_year_return": "12.23%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "Kotak small cap fund direct growth",
            "one_year_return": "0.55%",
            "three_year_return": "32.59%",
            "five_year_return": "15.63%",
            "risk": "high",
            "category": "equity",
        },
    ],
    "stocks": [
        {
            "name": "Apple Inc",
            "current_price": "$130.12",
            "one_month": "-10.72%",
            "three_months": "-11,54%",
            "one_year": "-29.74%",
            "five_year": "197.91%",
        },
        {
            "name": "Microsoft Corporation",
            "current_price": "$241.16",
            "one_month": "-2.41%",
            "three_months": "-1.25%",
            "one_year": "-31.41%",
            "five_year": "174.18%",
        },
        {
            "name": "Nvidia corporation",
            "current_price": "$145.79",
            "one_month": "-10.25%",
            "three_months": "14.86%",
            "one_year": "-53.21%",
            "five_year": "190.15%",
        },
        {
            "name": "Meta Platform Inc",
            "current_price": "$120.67",
            "one_month": "5.63%",
            "three_months": "-15.24%",
            "one_year": "-66.29%",
            "five_year": "-34.48%",
        },
        {
            "name": "Cisco System Inc",
            "current_price": "$47.61",
            "one_month": "-2.51%",
            "three_months": "16.02%",
            "one_year": "-26.41%",
            "five_year": "22.9%",
        },
    ],
    "crypto": [
        {"name": "Bitcoin", "price": "1439600", "category": "large_cap"},
        {"name": "Ethereum", "price": "102831", "category": "large_cap"},
        {"name": "Binance coin", "price": "21305", "category": "large_cap"},
        {"name": "Solana", "price": "800.26", "category": "large_cap"},
        {"name": "Tether", "price": "87.15", "category": "large_cap"},
        {"name": "Ripple", "price": "30.3", "category": "large_cap"},
        {"name": "Cardano", "price": "21.25", "category": "large_cap"},
        {"name": "Doge", "price": "6.25", "category": "large_cap"},
    ],
    "bonds": [
        [
            {
                "name": "UTI Bond Fund Direct Growth",
                "one_year_return": "10.28%",
                "three_year_return": "7.19%",
                "five_year_return": "-4.17%",
            },
            {
                "name": "Nippon India Income Fund (Growth)",
                "one_year_return": "-3.33%",
                "three_year_return": "4.96%",
                "five_year_return": "6.46%",
            },
            {
                "name": "ICICI Prudential Long Term Bond Fund Direct Plan Growth",
                "one_year_return": "-1.86%",
                "three_year_return": "4.71%",
                "five_year_return": "6.82%",
            },
            {
                "name": "Tata Income Fund Direct Growth",
                "one_year_return": "-0.50%",
                "three_year_return": "5.97%",
                "five_year_return": "-5.89%",
            },
            {
                "name": "LIC MF Bond Fund Growth",
                "one_year_return": "-2.85%",
                "three_year_return": "4.26%",
                "five_year_return": "5.26%",
            },
        ]
    ],
}


MID_RISK = {
    "mutual_funds": [
        {
            "name": "Quant Small Cap Fund Direct Growth",
            "one_year_return": "10.2%",
            "three_year_return": "55.2%",
            "five_year_return": "23.49%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "Quant tax plan direct growth",
            "one_year_return": "13%",
            "three_year_return": "40.12%",
            "five_year_return": "22.77%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "TATA small cap fund direct growth",
            "one_year_return": "10.9%",
            "three_year_return": "33.6%",
            "five_year_return": "12.23%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "Kotak small cap fund direct growth",
            "one_year_return": "0.55%",
            "three_year_return": "32.59%",
            "five_year_return": "15.63%",
            "risk": "high",
            "category": "equity",
        },
        {
            "name": "Quant Absolute Fund Direct Growth",
            "one_year_return": "14.19%",
            "three_year_return": "31.4%",
            "five_year_return": "19.49%",
            "risk": "high",
            "category": "hybrid",
        },
        {
            "name": "JM Equity hybrid fund direct growth",
            "one_year_return": "9.83%",
            "three_year_return": "20.4%",
            "five_year_return": "11.1%",
            "risk": "high",
            "category": "hybrid",
        },
        {
            "name": "ICICI prudential multi asset direct fund growth",
            "one_year_return": "18.1%",
            "three_year_return": "20.78%",
            "five_year_return": "13.57%",
            "risk": "high",
            "category": "hybrid",
        },
        {
            "name": "Kotak equity hybrid fund direct growth",
            "one_year_return": "7.17%",
            "three_year_return": "17.49%",
            "five_year_return": "12.3%",
            "risk": "high",
            "category": "hybrid",
        },
    ],
    "stocks": [
        {
            "name": "Apple Inc",
            "current_price": "$130.12",
            "one_month": "-10.72%",
            "three_months": "-11,54%",
            "one_year": "-29.74%",
            "five_year": "197.91%",
        },
        {
            "name": "Microsoft Corporation",
            "current_price": "$241.16",
            "one_month": "-2.41%",
            "three_months": "-1.25%",
            "one_year": "-31.41%",
            "five_year": "174.18%",
        },
        {
            "name": "Nvidia corporation",
            "current_price": "$145.79",
            "one_month": "-10.25%",
            "three_months": "14.86%",
            "one_year": "-53.21%",
            "five_year": "190.15%",
        },
        {
            "name": "Meta Platform Inc",
            "current_price": "$120.67",
            "one_month": "5.63%",
            "three_months": "-15.24%",
            "one_year": "-66.29%",
            "five_year": "-34.48%",
        },
        {
            "name": "Cisco System Inc",
            "current_price": "$47.61",
            "one_month": "-2.51%",
            "three_months": "16.02%",
            "one_year": "-26.41%",
            "five_year": "22.9%",
        },
    ],
    "crypto": [
        {"name": "Bitcoin", "price": "1439600", "category": "large_cap"},
        {"name": "Ethereum", "price": "102831", "category": "large_cap"},
        {"name": "Binance coin", "price": "21305", "category": "large_cap"},
        {"name": "Solana", "price": "800.26", "category": "large_cap"},
        {"name": "Tether", "price": "87.15", "category": "large_cap"},
        {"name": "Ripple", "price": "30.3", "category": "large_cap"},
        {"name": "Cardano", "price": "21.25", "category": "large_cap"},
        {"name": "Doge", "price": "6.25", "category": "large_cap"},
    ],
    "bonds": [
        [
            {
                "name": "UTI Bond Fund Direct Growth",
                "one_year_return": "10.28%",
                "three_year_return": "7.19%",
                "five_year_return": "-4.17%",
            },
            {
                "name": "Nippon India Income Fund (Growth)",
                "one_year_return": "-3.33%",
                "three_year_return": "4.96%",
                "five_year_return": "6.46%",
            },
            {
                "name": "ICICI Prudential Long Term Bond Fund Direct Plan Growth",
                "one_year_return": "-1.86%",
                "three_year_return": "4.71%",
                "five_year_return": "6.82%",
            },
            {
                "name": "Tata Income Fund Direct Growth",
                "one_year_return": "-0.50%",
                "three_year_return": "5.97%",
                "five_year_return": "-5.89%",
            },
            {
                "name": "LIC MF Bond Fund Growth",
                "one_year_return": "-2.85%",
                "three_year_return": "4.26%",
                "five_year_return": "5.26%",
            },
        ]
    ],
}

LOW_RISK = {
    "mutual_funds": [
        {
            "name": "JM low duration fund direct plan growth",
            "one_year_return": "4.61%",
            "three_year_return": "11.30%",
            "five_year_return": "5.30%",
            "risk": "Low ",
            "Category": "debt",
        },
        {
            "name": "UTI dynamic bond fund direct growth",
            "one_year_return": "10.86%",
            "three_year_return": "9.54%",
            "five_year_return": "6.17%",
            "risk": "low",
            "Category": "debt",
        },
        {
            "name": "HDFC fixed maturity plan 1141 days ",
            "one_year_return": "9.19%",
            "three_year_return": "9.52%",
            "five_year_return": "",
            "risk": "low",
            "Category": "debt",
        },
        {
            "name": "Bank of India short term income fund direct growth",
            "one_year_return": "27.43%",
            "three_year_return": "9.45%",
            "five_year_return": "4.04%",
            "risk": "low ",
            "Category": "debt",
        },
    ],
    "fd": [
        {
            "bank_name": "Kotak Mahindra Bank",
            "interest_rate": "7",
            "min_amount": "5000",
        },
        {"bank_name": "IND super Saver FD", "interest_rate": "8", "min_amount": "5000"},
        {
            "bank_name": "Bajaj Finance Ltd ",
            "interest_rate": "7.94",
            "min_amount": "15000",
        },
        {"bank_name": "ICICI Bank", "interest_rate": "7", "min_amount": "5000"},
        {"bank_name": "Axis Bank", "interest_rate": "6.9", "min_amount": "5000"},
    ],
    "rd": [
        {
            "tenure": "12 months",
            "bank_name": "Kotak Mahindra Bank",
            "interest_rate": "6.75",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "IND super Saver FD",
            "interest_rate": "8",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "Bajaj Finance Ltd ",
            "interest_rate": "7.94",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "ICICI Bank",
            "interest_rate": "5.7",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "Axis Bank",
            "interest_rate": "6",
            "min_amount": "1000",
        },
    ],
    "ppf": [{}],
    "nps": [{}],
}

VERY_LOW_RISK = {
    "fd": [
        {
            "bank_name": "Kotak Mahindra Bank",
            "interest_rate": "7",
            "min_amount": "5000",
        },
        {"bank_name": "IND super Saver FD", "interest_rate": "8", "min_amount": "5000"},
        {
            "bank_name": "Bajaj Finance Ltd ",
            "interest_rate": "7.94",
            "min_amount": "15000",
        },
        {"bank_name": "ICICI Bank", "interest_rate": "7", "min_amount": "5000"},
        {"bank_name": "Axis Bank", "interest_rate": "6.9", "min_amount": "5000"},
    ],
    "rd": [
        {
            "tenure": "12 months",
            "bank_name": "Kotak Mahindra Bank",
            "interest_rate": "6.75",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "IND super Saver FD",
            "interest_rate": "8",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "Bajaj Finance Ltd ",
            "interest_rate": "7.94",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "ICICI Bank",
            "interest_rate": "5.7",
            "min_amount": "1000",
        },
        {
            "tenure": "12 months",
            "bank_name": "Axis Bank",
            "interest_rate": "6",
            "min_amount": "1000",
        },
    ],
    "ppf": [{}],
}
